# T=int(input("enter a no."))
# for i in range(T):
#     A=int(input("enter a no."))
#     B=int(input("enter a no."))
#     C=A+B
#     print(C)



# t1=("banana","apple","guava")
# y=list(t1)
# y.pop()
# x=tuple(y)
# print(x)


# dict={"brand":"suzuki","model":"dzire","year":2003}
# print(dict)
# x=dict["model"]
# print(x)
# y=dict.get("model")
# print(y)
# for i in dict:
    # print(i)
    # print(dict[i])
# for i in dict.keys():
#     print(i)
# for x,y in dict.items():
#     print(x,y)
# dict["year"]=2018
# print(dict)

# if "model" in dict:
#     print("yes")
# else:
#     print("no")

# dict["colour"]="white"
# print(dict)

# print(len(dict))

# dict.pop("model")
# print(dict)
# dict.popitem()
# print(dict)
# del dict["year"]
# print(dict)

# del dict *****
# print(dict)

# dict.clear()
# print(dict)

# print(dict.copy())

# dict={}
# x=("firstkey","secondkey","thirdkey")
# y=0
# dict1=dict.fromkeys(x,y)
# print(dict1)

# dict.update({"year":2009})
# print(dict)

# dict.update({"location":"delhi"})
# print(dict)

# child1={"name":"madhu","year":2005}
# child2={"name":"priya","year":2002}
# child3={"name":"aman","year":1998}
# my_family={"child1":child1,
#            "child2":child2,
#            "child3":child3,}
# print(my_family)


# my_family={"child1":{"name":"madhu","year":2003},
# "child2":{"name":"priya","year":2002},
# "child3":{"name":"aman","year":1998}}
# print(my_family)


